"""final pkb schema

Revision ID: 851ef5c175dd
Revises: 573b2fa7e925
Create Date: 2025-12-10 13:31:21.749088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851ef5c175dd'
down_revision: Union[str, Sequence[str], None] = '573b2fa7e925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkb_products', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('pkb_products', sa.Column('category_6', sa.String(length=150), nullable=False))
    op.add_column('pkb_products', sa.Column('product_name', sa.String(length=255), nullable=True))
    op.add_column('pkb_products', sa.Column('weight', sa.String(length=50), nullable=True))
    op.alter_column('pkb_products', 'item_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pkb_products', 'brand_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('pkb_products', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('pkb_products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pkb_products', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('pkb_products', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pkb_products', 'brand_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('pkb_products', 'item_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('pkb_products', 'weight')
    op.drop_column('pkb_products', 'product_name')
    op.drop_column('pkb_products', 'category_6')
    op.drop_column('pkb_products', 'remarks')
    # ### end Alembic commands ###
