"""initial schema

Revision ID: acb510097808
Revises: 
Create Date: 2025-12-09 14:33:16.051336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acb510097808'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlets',
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('outlet_name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('outlet_id'),
    sa.UniqueConstraint('outlet_name')
    )
    op.create_index(op.f('ix_outlets_outlet_id'), 'outlets', ['outlet_id'], unique=False)
    op.create_table('pkb_products',
    sa.Column('pkb_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('article_name', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('rsp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pkb_id')
    )
    op.create_index(op.f('ix_pkb_products_barcode'), 'pkb_products', ['barcode'], unique=True)
    op.create_index(op.f('ix_pkb_products_pkb_id'), 'pkb_products', ['pkb_id'], unique=False)
    op.create_table('purchase_raw',
    sa.Column('raw_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=150), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=False),
    sa.Column('hsn_code', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('article_name_raw', sa.String(length=255), nullable=False),
    sa.Column('item_name_raw', sa.String(length=255), nullable=False),
    sa.Column('name_raw', sa.String(length=255), nullable=False),
    sa.Column('brand_name_raw', sa.String(length=150), nullable=False),
    sa.Column('size_raw', sa.String(length=100), nullable=False),
    sa.Column('pur_qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rsp_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp_raw', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cgst_raw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst_raw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cess_raw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst_raw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_raw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=150), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('raw_id')
    )
    op.create_index(op.f('ix_purchase_raw_raw_id'), 'purchase_raw', ['raw_id'], unique=False)
    op.create_table('outlet_aliases',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.outlet_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_index(op.f('ix_outlet_aliases_alias_id'), 'outlet_aliases', ['alias_id'], unique=False)
    op.create_table('pkb_update_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('pkb_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('changed_by', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['pkb_id'], ['pkb_products.pkb_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_pkb_update_log_log_id'), 'pkb_update_log', ['log_id'], unique=False)
    op.create_table('purchase_processed',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=True),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('pkb_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=False),
    sa.Column('article_name', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('pur_qty', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rsp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cess', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('batch_no', sa.String(length=100), nullable=True),
    sa.Column('mfg_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_by', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.outlet_id'], ),
    sa.ForeignKeyConstraint(['pkb_id'], ['pkb_products.pkb_id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['purchase_raw.raw_id'], ),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_index(op.f('ix_purchase_processed_purchase_id'), 'purchase_processed', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_processed_purchase_id'), table_name='purchase_processed')
    op.drop_table('purchase_processed')
    op.drop_index(op.f('ix_pkb_update_log_log_id'), table_name='pkb_update_log')
    op.drop_table('pkb_update_log')
    op.drop_index(op.f('ix_outlet_aliases_alias_id'), table_name='outlet_aliases')
    op.drop_table('outlet_aliases')
    op.drop_index(op.f('ix_purchase_raw_raw_id'), table_name='purchase_raw')
    op.drop_table('purchase_raw')
    op.drop_index(op.f('ix_pkb_products_pkb_id'), table_name='pkb_products')
    op.drop_index(op.f('ix_pkb_products_barcode'), table_name='pkb_products')
    op.drop_table('pkb_products')
    op.drop_index(op.f('ix_outlets_outlet_id'), table_name='outlets')
    op.drop_table('outlets')
    # ### end Alembic commands ###
